easy_admin:
  design:
    menu:
      - {label: "Entity"}
      - label: "Centre"
        children: 
          - {entity: Centre, label: "Liste Centres", icon: "th-list"}
          - {entity: Centre, label: "Nouveau centre", icon: "plus", params: {action: "new"}}

      - label: "Ville"
        children: 
          - {entity: Ville, label: "Liste Villes", icon: "th-list"}
          - {entity: Ville, label: "Nouvelle Ville", icon: "plus", params: {action: "new"}}

      - label: "Actualite"
        children: 
          - {entity: Actualite, label: "Liste Actualites", icon: "th-list"}
          - {entity: Actualite, label: "Nouvelle Actualite", icon: "plus", params: {action: "new"}}

      - label: "DG"
        children: 
          - {entity: DG, label: "Liste Directeurs", icon: "th-list"}
          - {entity: DG, label: "Nouveau DG", icon: "plus", params: {action: "new"}}

      - label: "Mot DG"
        children: 
          - {entity: DgWord, label: "Liste mot DG", icon: "th-list"}
          - {entity: DgWord, label: "Nouveau mot DG", icon: "plus", params: {action: "new"}}

      - label: "Organigramme"
        children: 
          - {entity: Organigramme, label: "Liste Organigrammes", icon: "th-list"}
          - {entity: Organigramme, label: "Nouveau Organigramme", icon: "plus", params: {action: "new"}}
      
      - label: "Spot"
        children: 
          - {entity: Spot, label: "Liste Spots", icon: "th-list"}
          - {entity: Spot, label: "Nouveau Spot", icon: "plus", params: {action: "new"}}
          
      - label: "Images couverture"
        children: 
          - {entity: ImagesEntete, label: "Liste Images", icon: "th-list"}
          - {entity: ImagesEntete, label: "Nouvelle image", icon: "plus", params: {action: "new"}}

      - label: "Label couverture"
        children: 
          - {entity: LabelCouverture, label: "Liste labels", icon: "th-list"}
          - {entity: LabelCouverture, label: "Nouveau label", icon: "plus", params: {action: "new"}}   

      - label: "Image Carousel"
        children: 
          - {entity: Carousel, label: "Liste Carousel", icon: "th-list"}
          - {entity: Carousel, label: "Nouvelle image", icon: "plus", params: {action: "new"}}

      - {label: "Paramètres"}
      - label: "Utilisateur"
        children: 
          - {entity: User, label: "Liste Utilisateur", icon: "th-list"}
          - {entity: User, label: "Nouveau Utilisateur", icon: "plus", params: {action: "new"}}