easy_admin:
  entities:

      # List the entity class name you want to manage
    Centre:
      class: App\Entity\Centre
      label: "Centre"
      form:
        fields:
          - type
          - adresse
          - grade_cc
          - nom_cc
          - num_cc
          - ville
          - annexe
          - { property: 'imageFile', type: 'vich_image' }
          
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Liste des centres "
        fields:
          - {property: 'ville.faritany', label: 'Faritany'} 
          - ville
          - adresse
          - {property: 'filename',label: 'Photo', type: 'image', base_path: '%centre_image_path%'}

      show:
        fields:
          - type
          - adresse
          - grade_cc
          - nom_cc
          - num_cc
          - ville
          - annexe
          - {property: 'filename', label: Photo ,type: 'image', base_path: '%centre_image_path%'}
       
      # edit:
      #   help: "hello there"
      #   fields:
      #     - '-tags'
