easy_admin:
  entities:
    ImagesEntete:
      class: App\Entity\ImagesEntete
      # templates:
      #   show: 'easyadmin/actualite/show.html.twig'
      #   edit: 'easyadmin/actualite/edit.html.twig'
      label: "Images En tête"
      form:
        fields:
          - labelCouverture
          - { property: 'imageFile', type: 'vich_image' }
          
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Liste Images"
        fields: [ 'labelCouverture', {property: 'filename', type: 'image', base_path: '%entete_image_path%'} ]

      show:
        fields:
          - labelCouverture
          - {property: 'filename', type: 'image', base_path: '%entete_image_path%'}

      edit:
        help: "hello there"
        fields:
          - '-tags'