easy_admin:
  entities:
    LabelCouverture:
      class: App\Entity\LabelCouverture
      # templates:
      #   show: 'easyadmin/actualite/show.html.twig'
      #   edit: 'easyadmin/actualite/edit.html.twig'
      label: "Label Couverture"
      form:
        fields:
          - label
          
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Liste Images"
        fields: [ 'label' ]

      show:
        fields:
          - label

      edit:
        help: "hello there"
        fields:
          - '-tags'